build->compilation
soetz/vite-docs-fr pull request #38
Opened 2022-02-19 02:58 UTC by Marr11317

2022-02-19 13:02 UTC, soetz requested changes
Ça rend le tout beaucoup plus clair c’est top, je me sens presque idiot de ne pas y avoir pensé plus tôt haha (après c’est à ça que servent les reviews)

Ceci dit il est important de garder en tête que build et compilation [ce n’est pas exactement la même chose](https://softwareengineering.stackexchange.com/a/140340). Dans ce cas, je pense que ce qu’on gagne en clarté d’explication surpasse ce qu’on perd en confusion entre les deux termes.

Attention cependant, si l’on est un débutant complet, il est possible qu’on ne fasse pas le lien directement entre le terme « build » quand il est encore utilisé (par exemple la commande `vite build`) et la compilation. Ce serait bien si tu pouvais faire une passe sur tous les endroits où « build » est toujours utilisé littéralement pour vérifier qu’on comprend bien que ce dont on parle peut être appelé compilation ailleurs.

Un exemple :
Dans [la partie mode de /config](https://github.com/Marr11317/vite-docs-fr/blob/patch-2/config/index.md#mode), j’ajouterais peut-être

```diff
- - **Valeur par défaut :** `'development'` pour `serve`, `'production'` pour `build`
+ - **Valeur par défaut :** `'development'` pour `serve`, `'production'` pour `build` (compilation)
```

Sinon, je ne sais pas ce que c’est que ce fichier `in.diff` mais il faudrait éventuellement l’enlever.

2022-02-19 23:24 UTC, Marr11317 commented on .vitepress/config.js
> +              text: 'Compilation de production',
J'ai hésité à mettre "Compilation en mode production" à tous ces endroits là, mais j'ai trouvé que ca devenait lourd. Est-ce que ca vaudrait mieux?

2022-02-19 23:27 UTC, Marr11317 commented on guide/build.md
> +La compilation peut être customisé à l’aide de ses diverses [options de configuration](/config/#options-de-compilation). Plus spécifiquement, vous pouvez ajuster les [options du Rollup](https://rollu
Personnalisée?

2022-02-19 23:31 UTC, Marr11317 commented on guide/api-plugin.md
> +La convention de Vite pour les modules virtuels est de préfixer le chemin visible par l’utilisateur par `virtual:`. Si possible le nom du plugin devrait être utilisé comme un namespace pour éviter d’
C'est que c'est une seule très grande ligne. C'est un autre "compilation" plus loin.

2022-02-19 23:34 UTC, Marr11317 commented on guide/assets.md
> +// il sera inclut à un morceau (chunk) différent pour la compilation de production
Comme ca?

2022-02-19 23:49 UTC, Marr11317 commented on guide/index.md
> +    "preview": "vite preview" // prévisualise la compilation de production en local
On met la limite à 80, c'est bien ca?

2022-02-19 23:50 UTC, Marr11317 commented on guide/api-plugin.md
> +La convention de Vite pour les modules virtuels est de préfixer le chemin visible par l’utilisateur par `virtual:`. Si possible le nom du plugin devrait être utilisé comme un namespace pour éviter d’
![image](https://user-images.githubusercontent.com/35939574/154822974-5eafbe8f-9bf4-45a6-ab66-96c6f69dd9de.png)

2022-02-20 22:29 UTC, soetz commented on guide/build.md
> +La compilation peut être customisé à l’aide de ses diverses [options de configuration](/config/#options-de-compilation). Plus spécifiquement, vous pouvez ajuster les [options du Rollup](https://rollu
Qu’est-ce qui te gène avec customisée ?

2022-02-20 22:36 UTC, soetz approved these changes

2022-02-20 22:36 UTC, soetz commented on guide/assets.md
> +// il sera inclus à un morceau (chunk) différent pour la compilation de production
```suggestion
// il sera inclus à un morceau (chunk) différent pour la compilation de
// production
```

2022-02-21 02:57 UTC, Marr11317 commented on guide/build.md
> +La compilation peut être customisé à l’aide de ses diverses [options de configuration](/config/#options-de-compilation). Plus spécifiquement, vous pouvez ajuster les [options du Rollup](https://rollu
Haha, je suis Québecois, et on a pas les mêmes anglicismes.

Les deux sont très compréhensibles, mais si le but est de traduire, je suis pour traduire tout ce qui peut se faire sans perdre de clarté.

2022-02-21 02:58 UTC, Marr11317 commented
Faut-il que je rebase? histoire de faire disparaître tous ces petits commits.

2022-02-21 16:01 UTC, soetz commented on guide/build.md
> +La compilation peut être customisé à l’aide de ses diverses [options de configuration](/config/#options-de-compilation). Plus spécifiquement, vous pouvez ajuster les [options du Rollup](https://rollu
Oui justement c’est quelque chose que j’apprécie !

Les deux me vont, « modifiée » aussi si tu veux couper la poire en deux, je te laisse utiliser le mot que tu préfères ;)

2022-02-21 16:02 UTC, soetz commented
> Faut-il que je rebase? histoire de faire disparaître tous ces petits commits. Je les condense en un seul?

Tu peux laisser tel quel, GitHub permet de condenser automatiquement :)

2022-02-21 19:31 UTC, soetz approved these changes

2022-02-21 19:40 UTC, merged